// generated by Fast Light User Interface Designer (fluid) version 1,0104

#include "ui.H"

Fl_Double_Window *main_w=(Fl_Double_Window *)0;

static void cb_main_w(Fl_Double_Window*, void*) {
  fjtag_exit();
}

static void cb_Exit(Fl_Menu_*, void*) {
  fjtag_exit();
}

static void cb_Check(Fl_Menu_*, void*) {
  log("Checking cable ...");
fjtag.setup_cable((int)(cable_type_ch->mvalue())->user_data(),port_select_ch->text());
fjtag.update_status();
}

static void cb_IDCODE(Fl_Menu_*, void*) {
  log(">instruction IDCODE");
fjtag.run("instruction IDCODE");
fjtag.run("shift ir");
fjtag.run("shift dr");
fjtag.run("dr");
}

static void cb_USERCODE(Fl_Menu_*, void*) {
  log(">instruction USERCODE");
fjtag.run("instruction USERCODE");
fjtag.run("shift ir");
fjtag.run("shift dr");
fjtag.run("dr");
}

static void cb_EXTEST(Fl_Menu_*, void*) {
  log(">instruction EXTEST");
fjtag.run("instruction EXTEST");
fjtag.run("shift ir");
fjtag.run("shift dr");
fjtag.run("dr");
}

static void cb_SAMPLE(Fl_Menu_*, void*) {
  log(">instruction SAMPLE/PRELOAD");
fjtag.run("instruction SAMPLE/PRELOAD");
fjtag.run("shift ir");
fjtag.run("shift dr");
fjtag.run("dr");
}

static void cb_CAPTURE(Fl_Menu_*, void*) {
  log(">instruction CAPTURE");
fjtag.run("instruction CAPTURE");
fjtag.run("shift ir");
fjtag.run("shift dr");
fjtag.run("dr");
}

static void cb_Shift(Fl_Menu_*, void*) {
  log(">shift ir");
fjtag.run("shift ir");
}

static void cb_Shift1(Fl_Menu_*, void*) {
  log(">shift dr");
fjtag.run("shift dr");
}

static void cb_View(Fl_Menu_*, void*) {
  log(">dr out");
fjtag.run("dr out");
}

static void cb_View1(Fl_Menu_*, void*) {
  log(">dr in");
fjtag.run("dr in");
}

static void cb_Clear(Fl_Menu_*, void*) {
  log_br->clear();
}

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, 4, 0, 14, 56},
 {"Load chain", 0x8006f,  (Fl_Callback*)open_flash_image, 0, 0, 3, 0, 14, 56},
 {"Save chain", 0x80073,  (Fl_Callback*)save_flash_image, 0, 128, 3, 0, 14, 56},
 {"Preferences", 0x80070,  (Fl_Callback*)preferences, 0, 128, 3, 0, 14, 56},
 {"Exit", 0x80078,  (Fl_Callback*)cb_Exit, 0, 0, 3, 0, 14, 56},
 {0},
 {"Jtag", 0,  0, 0, 64, 4, 0, 14, 56},
 {"Check cable", 0x80063,  (Fl_Callback*)cb_Check, 0, 0, 3, 0, 14, 56},
 {"Autodetect chain", 0x80064,  (Fl_Callback*)autodetect_chain, 0, 0, 3, 0, 14, 56},
 {"Autodetect flash", 0x80066,  (Fl_Callback*)autodetect_flash, 0, 0, 3, 0, 14, 56},
 {"Set netlist", 0x8006e,  0, 0, 0, 3, 0, 14, 56},
 {"Test interconnection", 0x80074,  0, 0, 0, 3, 0, 14, 56},
 {"Instructions", 0,  0, 0, 64, 3, 0, 14, 56},
 {"IDCODE", 0x49,  (Fl_Callback*)cb_IDCODE, 0, 0, 3, 0, 14, 56},
 {"USERCODE", 0x55,  (Fl_Callback*)cb_USERCODE, 0, 0, 3, 0, 14, 56},
 {"EXTEST", 0x45,  (Fl_Callback*)cb_EXTEST, 0, 0, 3, 0, 14, 56},
 {"SAMPLE/PRELOAD", 0x53,  (Fl_Callback*)cb_SAMPLE, 0, 0, 3, 0, 14, 56},
 {"CAPTURE", 0x43,  (Fl_Callback*)cb_CAPTURE, 0, 0, 3, 0, 14, 56},
 {0},
 {"Commands", 0,  0, 0, 64, 3, 0, 14, 56},
 {"Shift IR", 0,  (Fl_Callback*)cb_Shift, 0, 0, 3, 0, 14, 56},
 {"Shift DR", 0,  (Fl_Callback*)cb_Shift1, 0, 0, 3, 0, 14, 56},
 {"View DR (out)", 0,  (Fl_Callback*)cb_View, 0, 0, 3, 0, 14, 56},
 {"View DR (in)", 0,  (Fl_Callback*)cb_View1, 0, 0, 3, 0, 14, 56},
 {0},
 {0},
 {"Tools", 0,  0, 0, 64, 4, 0, 14, 56},
 {"Flash", 0,  0, 0, 64, 3, 0, 14, 56},
 {"Blank check flash", 0,  0, 0, 0, 3, 0, 14, 56},
 {"Erase entire flash", 0,  0, 0, 0, 3, 0, 14, 56},
 {"Erase flash sector", 0,  0, 0, 0, 3, 0, 14, 56},
 {"Read flash", 0,  0, 0, 0, 3, 0, 14, 56},
 {"Program flash", 0,  0, 0, 0, 3, 0, 14, 56},
 {"Verify flash", 0,  0, 0, 0, 3, 0, 14, 56},
 {0},
 {"Programmer", 0,  0, 0, 65, 3, 0, 14, 56},
 {0},
 {"CPU", 0,  0, 0, 193, 3, 0, 14, 56},
 {0},
 {"Clear message browser", 0,  (Fl_Callback*)cb_Clear, 0, 0, 3, 0, 14, 56},
 {0},
 {"Autodetect chain", 0,  (Fl_Callback*)autodetect_chain, 0, 0, 4, 0, 14, 56},
 {"Autodetect flash", 0,  (Fl_Callback*)autodetect_flash, 0, 0, 4, 0, 14, 56},
 {"                                             ", 0,  0, 0, 1, 0, 0, 14, 56},
 {"Help", 0,  0, 0, 64, 4, 0, 14, 56},
 {"About", 0,  0, 0, 0, 3, 0, 14, 56},
 {0},
 {0}
};

Fl_Output *status_bar=(Fl_Output *)0;

Fl_Browser *parts_br=(Fl_Browser *)0;

Fl_Browser *pins_br=(Fl_Browser *)0;

Fl_Browser *bus_br=(Fl_Browser *)0;

Fl_Browser *flash_br=(Fl_Browser *)0;

Fl_Browser *log_br=(Fl_Browser *)0;

Fl_History_Input *cmd_i=(Fl_History_Input *)0;

static void cb_cmd_i(Fl_History_Input*, void*) {
  if (cmd_i->size()) {
 log(">%s", cmd_i->value());
 fjtag.run(cmd_i->value());
 fjtag.update_status();
 cmd_i->value(0);
};
}

Fl_Double_Window *prefs_w=(Fl_Double_Window *)0;

static void cb_Cancel(Fl_Button*, void*) {
  prefs_w->hide();
}

Fl_Choice *cable_type_ch=(Fl_Choice *)0;

Fl_Menu_Item menu_cable_type_ch[] = {
 {"None", 0,  0, (void*)(0), 0, 0, 14, 14, 56},
 {"Altera Byteblaster(II/MV)", 0,  0, (void*)(1), 0, 0, 14, 14, 56},
 {0}
};

Fl_Choice *port_select_ch=(Fl_Choice *)0;

Fl_Menu_Item menu_port_select_ch[] = {
 {"None", 0,  0, 0, 0, 0, 14, 14, 56},
 {"/dev/parport0", 0,  0, 0, 0, 0, 14, 14, 56},
 {"/dev/parport1", 0,  0, 0, 0, 0, 14, 14, 56},
 {"/dev/parport2", 0,  0, 0, 0, 0, 14, 14, 56},
 {"/dev/parport3", 0,  0, 0, 0, 0, 14, 14, 56},
 {0}
};

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = main_w = new Fl_Double_Window(695, 443, "FJtag");
    w = o;
    o->callback((Fl_Callback*)cb_main_w);
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 694, 21);
      o->color(FL_DARK1);
      o->menu(menu_);
    }
    { Fl_Output* o = status_bar = new Fl_Output(0, 421, 694, 21);
      o->tooltip("Status Bar");
      o->box(FL_THIN_UP_BOX);
      o->color(FL_DARK1);
      o->textfont(8);
      o->textsize(15);
      o->textcolor(136);
      o->align(FL_ALIGN_CENTER);
      Fl_Group::current()->resizable(o);
    }
    { Fl_Browser* o = parts_br = new Fl_Browser(1, 40, 215, 241, "Parts");
      o->type(3);
      o->color(FL_DARK1);
      o->selection_color((Fl_Color)92);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelcolor(FL_DARK_GREEN);
      o->textfont(8);
      o->textsize(17);
      o->callback((Fl_Callback*)part_br_cb);
      o->align(FL_ALIGN_TOP);
    }
    { Fl_Browser* o = pins_br = new Fl_Browser(216, 40, 186, 241, "Pins");
      o->type(3);
      o->color(FL_DARK1);
      o->selection_color((Fl_Color)92);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelcolor(FL_DARK_GREEN);
      o->textfont(8);
      o->textsize(13);
      o->callback((Fl_Callback*)pins_br_cb);
      o->align(FL_ALIGN_TOP);
    }
    { Fl_Browser* o = bus_br = new Fl_Browser(389, 40, 72, 241, "Bus");
      o->type(3);
      o->color(FL_DARK1);
      o->selection_color((Fl_Color)92);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelcolor(FL_DARK_GREEN);
      o->textfont(8);
      o->textsize(15);
      o->align(FL_ALIGN_TOP);
      o->hide();
      o->deactivate();
    }
    { Fl_Browser* o = flash_br = new Fl_Browser(402, 40, 291, 241, "Flash chip");
      o->color(FL_DARK1);
      o->selection_color((Fl_Color)92);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelcolor(FL_DARK_GREEN);
      o->textfont(8);
      o->textsize(12);
      o->align(FL_ALIGN_TOP);
    }
    { Fl_Browser* o = log_br = new Fl_Browser(1, 281, 692, 120);
      o->tooltip("Messages area");
      o->type(2);
      o->color(FL_DARK1);
      o->selection_color((Fl_Color)92);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelcolor(FL_DARK_GREEN);
      o->textfont(8);
      o->textsize(15);
      o->align(FL_ALIGN_TOP);
    }
    { Fl_History_Input* o = cmd_i = new Fl_History_Input(0, 401, 694, 21);
      o->tooltip("Command Input (Obsolete)");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)139);
      o->selection_color(FL_DARK1);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->textfont(1);
      o->textcolor(93);
      o->callback((Fl_Callback*)cb_cmd_i);
      o->align(FL_ALIGN_LEFT);
      o->when(FL_WHEN_ENTER_KEY_ALWAYS);
      cmd_i->cursor_color(cmd_i->textcolor());
    }
    o->end();
  }
  { Fl_Double_Window* o = prefs_w = new Fl_Double_Window(323, 189, "Preferences");
    w = o;
    { Fl_Button* o = new Fl_Button(28, 145, 102, 22, "Ok");
      o->color(FL_DARK1);
      o->selection_color((Fl_Color)40);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelfont(13);
      o->labelcolor(FL_GRAY0);
      o->callback((Fl_Callback*)prefs_ok);
    }
    { Fl_Button* o = new Fl_Button(191, 145, 102, 22, "Cancel");
      o->color(FL_DARK1);
      o->selection_color((Fl_Color)40);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelfont(13);
      o->labelcolor(FL_GRAY0);
      o->callback((Fl_Callback*)cb_Cancel);
    }
    { Fl_Choice* o = cable_type_ch = new Fl_Choice(19, 36, 284, 23, "Cable type");
      o->down_box(FL_BORDER_BOX);
      o->color((Fl_Color)43);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelfont(13);
      o->align(FL_ALIGN_TOP);
      o->menu(menu_cable_type_ch);
    }
    { Fl_Choice* o = port_select_ch = new Fl_Choice(19, 92, 284, 23, "Port select");
      o->down_box(FL_BORDER_BOX);
      o->color((Fl_Color)43);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelfont(13);
      o->align(FL_ALIGN_TOP);
      o->menu(menu_port_select_ch);
    }
    o->set_modal();
    o->end();
  }
  return w;
}
